id: I713948CE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:01:48+00:00'
last_modified: '2022-06-07T18:40:23.047470+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25254
  title: གངས་ཅན་བོད་ཡུལ་དུ་སྤྲིངས་པའི་འཕྲིན་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    74AB:
      image_group_id: I4746
      title: ''
      total_pages: 254
      order: 1
      base_file: 74AB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
