id: P003254
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W25254
  title: གངས་ཅན་བོད་ཡུལ་དུ་སྤྲིངས་པའི་འཕྲིན་ཡིག
  author: ''
  volumes:
    57a104ee93474b998f7cc0b858bb5af0:
      image_group_id: I4746
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
